### ISSUE TITLE
Unable to compile ble_app_hrs with pure-gcc

### ISSUE THREAD

**Issue by MadmanSmoker** [hlnd/nrf51-pure-gcc-setup#14] opened 2014-07-06 06:19 UTC
I compiled and ran the blinky_test using the pure-gcc setup. However when I do the same for the ble_app_hrs it does not seem to work

I have followed the given steps:
1-flash a softdevice onto the board using make flash-softdevice SOFTDEVICE=/path/to/version/6
2-Copy the make file in the examples directory:
../main.c:44:28: fatal error: device_manager.h: No such file or directory
 #include "device_manager.h"
                            ^
compilation terminated.
make: **\* [_build/main.o] Error 1
3: I added the required path as follow to the make file:

LIBRARY_PATHS = "$(SDK_PATH)Include/s110"
LIBRARY_PATHS += "$(SDK_PATH)Include/ble"
LIBRARY_PATHS += "$(SDK_PATH)Include/ble/device_manager"
LIBRARY_PATHS += "$(SDK_PATH)Include/ble/ble_services"
LIBRARY_PATHS += "$(SDK_PATH)Include/app_common"
LIBRARY_PATHS += "$(SDK_PATH)Include/sd_common"
LIBRARY_PATHS += "$(SDK_PATH)Include/sdk"
LIBRARY_PATHS += "/home/username/Desktop/nordic/nrf51_sdk_v6_0_0_43681/nrf51822/Include/ble/device_manager"
4.Now I end up with this error:
make: **\* No rule to make target `_build/ble_bondmngr.o', needed by`all'.  Stop.
SO I added these 4 paths as source files:
SOURCE_PATHS += $(SDK_PATH)Source/ble

SOURCE_PATHS += $(SDK_PATH)Source/ble/device_manager

SOURCE_PATHS += $(SDK_PATH)Source/app_common

SOURCE_PATHS += $(SDK_PATH)Source/sd_common

It still throws the same error. Could you please help me out?

**Comment by eliotstock** [comment] 2014-07-06 12:41
You probably want either the device manager or the bond manager in the build, but not both. Try taking ble_bondmngr.c out of the list of sources (APPLICATION_SRCS) at the top of the Makefile you copied into your project.

**Comment by MadmanSmoker** [comment] 2014-07-07 03:21
That seems to be the issue. Thanks for the help.

**Comment by hlnd** [comment] 2014-07-19 23:11
I'm terribly sorry for the late response, but I've been on vacation... The root cause here seems to be that the setup hadn't been updated to work with SDK 6.0.0, which was the first version to use the device manager for the peripheral projects. This has now been fixed, and if you update to latest master, things should work. I've also added a note in the readme to state which version is currently supported.

Also beware that adding library paths to the project makefile is normally not necessary: setting USE_SOFTDEVICE to 's110' without quotes (beware the case) should be sufficient. 

I'm closing this, but let me know if you have any further problems!

**Closed as completed by hlnd** 2014-07-19 23:11 UTC
